### Advance Operation With Business Examples

In [2]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [8]:
# Data Structure : [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]
])

print("Foodpanda sales analysis: ")
print("\nSales data shapes : ", sales_data.shape)
print("\nSample data for 1st 3 restaurant : \n", sales_data[0:3])

Foodpanda sales analysis: 

Sales data shapes :  (5, 5)

Sample data for 1st 3 restaurant : 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [13]:
# total sales per year
print(np.sum(sales_data, axis=0))
per_year = np.sum(sales_data[:, 1:], axis=0)
print(per_year)


# minimum sales per restaurant
min_sales = np.min(sales_data[:, 1:], axis=1)
print(min_sales)

# maximum sales per restaurant
max_sales = np.max(sales_data[:, 1:], axis=0)
print(max_sales)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
