### Numpy array operations

In [ ]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing : ", arr[2:7]) ##2nd element excluded
print("With step slicing : ", arr[1:8:2])
print("Negative indexing : ", arr[-3])

Basic slicing :  [3 4 5 6 7]
With step slicing :  [2 4 6 8]
Negative indexing :  8


In [5]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element : ", arr_2d[1,2])
print("Entire row : ", arr_2d[1])
print("Entire column : ", arr_2d[:,2])

Specific element :  6
Entire row :  [4 5 6]
Entire column :  [3 6 9]


### Sorting

In [6]:
unsorted = np.array([2,4,1,3,5,0,9,6,3,7])
print("Sorted array : ", np.sort(unsorted))

unsorted_2d_arr = ([[3,1],
                    [1,2],
                    [2,3]])
print("Sorted 2d array by row : ", np.sort(unsorted_2d_arr, axis=0)) ## Top to Bottom

Sorted array :  [0 1 2 3 3 4 5 6 7 9]
Sorted 2d array by row :  [[1 1]
 [2 2]
 [3 3]]


### Filtering

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even number : ", even_number)

odd_number = numbers[numbers % 2 != 0]
print("Odd number : ", odd_number)

Even number :  [ 2  4  6  8 10]
Odd number :  [1 3 5 7 9]


### Filter with mask

In [8]:
mask = numbers > 5
print("Numbers greater than 5 : ", numbers[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


### Fancy indexing Vs np.where()

In [9]:
indices = [0, 2, 4]
print(numbers[indices])

where_cluse = np.where(numbers > 5)
print("Numpy where cluse : ",numbers[where_cluse])

[1 3 5]
Numpy where cluse :  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers * 5, numbers)
print(condition_array)

## for better understanding
condition_array = np.where(numbers > 5, True, False)
print(condition_array)

"""
Works like
if(numbers > 5)
    numbers * 5
else
    numbers
"""

[ 1  2  3  4  5 30 35 40 45 50]
[False False False False False  True  True  True  True  True]


### Adding and removing data

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [4]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,9])
arr3 = np.array([10,11,12,13])

print("Compatibility Shapes : ", arr1.shape == arr2.shape)

Compatibility Shapes :  False


In [8]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))
print("With new row : \n", with_new_row )

new_column = np.array([[7], [8]])
with_new_column = np.hstack((original, new_column))
print("With new column :\n", with_new_column)


With new row : 
 [[1 2]
 [3 4]
 [5 6]]
With new column :
 [[1 2 7]
 [3 4 8]]


In [9]:
arr = np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr, 3)
print("Array after deletion : ", deleted)

Array after deletion :  [1 2 3 5 6 7]
