## Notebook

In [3]:
print("Hello")

Hello


In [4]:
import numpy as np

## Create array from list

In [5]:
arr_1d = ([1,2,3,4])
print("1D array : ", arr_1d)

arr_2d = ([[1,2,3,4], [5,6,7,8]])
print("2D array : ", arr_2d)

1D array :  [1, 2, 3, 4]
2D array :  [[1, 2, 3, 4], [5, 6, 7, 8]]


## List Vs Numpy

In [6]:
import time

py_list = [1,2,3,4]
print("Python list multiplication : ", py_list * 2)

np_array = np.array([1,2,4])
print("Numpy array multiplication : ", np_array * 2)

##check optimization
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time : ", time.time() - start)



Python list multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication :  [2 4 8]

 List operation time :  0.08722829818725586

 Numpy operation time :  0.006404399871826172


### Creating array from scratch

In [7]:
zeros = np.zeros((3,4))
print("Zeros array : \n", zeros)

Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
