## Notebook

In [3]:
print("Hello")

Hello


In [2]:
import numpy as np

## Create array from list

In [5]:
arr_1d = ([1,2,3,4])
print("1D array : ", arr_1d)

arr_2d = ([[1,2,3,4], [5,6,7,8]])
print("2D array : ", arr_2d)

1D array :  [1, 2, 3, 4]
2D array :  [[1, 2, 3, 4], [5, 6, 7, 8]]


## List Vs Numpy

In [6]:
import time

py_list = [1,2,3,4]
print("Python list multiplication : ", py_list * 2)

np_array = np.array([1,2,4])
print("Numpy array multiplication : ", np_array * 2)

##check optimization
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time : ", time.time() - start)



Python list multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication :  [2 4 8]

 List operation time :  0.08722829818725586

 Numpy operation time :  0.006404399871826172


### Creating array from scratch

In [7]:
zeros = np.zeros((3,4))
print("Zeros array : \n", zeros)


ones = np.ones((2,3))
print("Ones array : \n", ones)

full = np.full((2,3), 7)
print("Full array : \n", full)

random = np.random.random((2,3))
print("Random array : \n", random)

sequence = np.arange(0,11, 2)
print("Sequence array : \n", sequence)


Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array : 
 [[7 7 7]
 [7 7 7]]
Random array : 
 [[0.29892762 0.47655699 0.50631228]
 [0.37700889 0.56452323 0.45011661]]
Sequence array : 
 [ 0  2  4  6  8 10]


### Vector, Metrix & Tensor

In [12]:
vector = np.array([1, 2, 3, 4])
print("Vector : ", vector)

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print("Matrix : ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("Tensor : ", tensor)

Vector :  [1 2 3 4]
Matrix :  [[1 2 3 4]
 [5 6 7 8]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array propertise

In [13]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape : ", arr.shape)
print("Dimention : ", arr.ndim)
print("Size : ", arr.size)
print("DataType : ", arr.dtype)

Shape :  (2, 3)
Dimention :  2
Size :  6
DataType :  int64


### Array reshaping

In [21]:
arr = np.arange(12)
print("Original array : ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array : ", reshaped)

flattened = reshaped.flatten()
print("Flattened array : ", flattened)

## Ravel returns view instead of copy
raveled = reshaped.ravel()
print("Ravaled array : ", raveled)

## Transpose
transpose = reshaped.T
print("Transpose array : ", transpose)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravaled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
